name: Coverage Report

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
        pip install -e .

    - name: Run tests
      run: |
        coverage run --source simplecep -m pytest
        coverage report -m

    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: Tests

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Publish coverage
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
